;; All of my spellcheck hotstrings.

;------------------------------------------------------------------------------
; Fix for -ign instead of -ing.
;------------------------------------------------------------------------------
#Hotstring B0  ; Turns off automatic backspacing for the following hotstrings.
::align::align
::assign::assign
::benign::benign
::campaign::campaign
::champaign::champaign
::cosign::cosign
::design::design
::ensign::ensign
::feign::feign
::foreign::foreign
::misalign::misalign
::outdesign::outdesign
::overdesign::overdesign
::preassign::preassign
::realign::realign
::reassign::reassign
::redesign::redesign
::reign::reign
::resign::resign
::sign::sign
::sovereign::sovereign
::unbenign::unbenign
 ; This makes the above hotstrings do nothing so that they override the ign->ing rule below.

#Hotstring B  ; Turn back on automatic backspacing for all subsequent hotstrings.
:?:ign::ing


;------------------------------------------
; Word endings
;------------------------------------------
:?:bilites::bilities
:?:bilties::bilities
:?:blities::bilities
:?:bilty::bility
:?:blity::bility
:?:, btu::, but ; Not just replacing "btu", as that is a unit of heat.
:?:; btu::; but
:?:n;t::n't
:?:;ll::'ll
:?:;re::'re
:?:;ve::'ve
::sice::since  ; Must precede the following line!
:?:sice::sive
:?:t eh:: the
:?:t hem:: them
:?:emnt::ment


;------------------------------------------
; Word Corrections
;------------------------------------------
:*:jsut::just
:*:leik::like
:*:liek::like
:*:tommorow::tomorrow
:*:desing::design
:*:socail::social
:*:amny::many
:*:ahve::have
:*:becasue::because
:*:ahev::have
:*:mpa::map
:*:mpas::maps
:*:paly::play
:*:palce::place
::doen::done
:*:lsit::list
:*:lvoe::love
:*:laod::load
:*:laoding::loading
::ym::my
::mena::mean
:*:rpoblem::problem
:*:eclispe::eclipse
:*:tlaking::talking
:*:tlak::talk
:*:remvoe::remove
:*:mvoe::move
:*:remvoed::removed
:*:arrya::array
:*:foudn::found
:*:soemthing::something
:*:serivce::service
:*:ahndle::handle
:*:postion::position
:*:wdith::width
:*:aling::align
:*:positon::position
:*:hieght::height
:*:piad ::paid
:*:cuase::cause
::eb::be
:*:thnaks::thanks
:*:knwo::know
:*:altin::latin
:*:oen::one
:*:ahven't::haven't
:*:almsot::almost
:*:gutair::guitar
:*:abnd::band
:*:suddel::subtle
:*:suddle::subtle
:*:hye::hey
:*:mordern::modern
:*:rbah::brah
:*:fidn::find
:*:bale::able
::dya::day
:*:poeple::people
:*:testr::tester
:*:behidn::behind
:*:rember::remember
:*:reaplce::replace
:*:amoutn::amount
:*:voer::over
:*:kidn::kind
:*:hwo::how
:*:wlak::walk
:*:soem::some
:*:thoguht::thought
:*:finsih::finish
:*:watn::want
:*:priavte::private
:*:eahc::each
:*:mna::man
:*:chnage::change
:*:amke::make
:*:yeha::yeah
:*:flase::false
:*:clac::calc
:*:hpone::phone
:*:ratehr::rather
:*:chirs::chris
:*:wokring::working
:*:tset::test
:*:msut::must
:*:thansk::thanks
:*:coutn::count
:*:woudl::would
:*:realtive::relative
:*:waht::what
:*:text-aling::text-align
:*:freind::friend
:*:tiem::time
:*:arounf::around
:*:smaple::sample
:*:lvie::live
:*:meachanize::mechanize
:*:alos::also
:*:whta::what
:*:mayeb::maybe
:*:eamil::email
:*:emssage::message
:*:lsot::lost
:*:anme::name
:*:realted::related
:*:I;ve::I've
:*:sicne::since
:*:immeadately::immediately
:*:whast::whats
:*:qork::work
:*:coem::come
:*:wnat::want
:*:fial::fail
:*:secodn::second
:*:remidn::remind
:*:cna::can
:*:wrok::work
:*:abotu::about
:*:reutnr::return
:*:flost::float
:*:excatly::exactly
:*:palnts::plants
:*:soudn::sound
:*:the the::the
:*:becuase::because
:*:abck::back
:*:tets::test
:*:amde::made
:*:ehads::heads
:*:woek::woke
:*:ahte::hate
:*:sakught::skaught
:*:flaot::float
:*:charcater::character
:*:ahrd::hard
:*:ebtter::better
:*:onyl::only
:*:vien::vein
:*:poitn::point
:*:amtch::match
:*:turly::truly
:*:relaise::realize
:*:baord::board
:*:falw::flaw
:*:ajred::jared
:*:alst::last
:*:presetn::present
:*:thsi::this
:*:expalin::explain
:*:udner::under
:*:groudn::ground
:*:sned::send
:*:it;s::it's
:*:anem::name
:*:sapce::space
:*:chgr::chr
:*:langauge::language
:*:ahd::had
:*:tolskdorf::tolksdorf
:*:aroudn::around
:*:haev::have
:*:breif::brief
:*:aslo::also
:*:porject::project
:*:porgress::progress
:*:calss::class
:*:toogle::toggle
:*:realised::realized
:*:lday::lady
:*:ranage::range
:*:upll::pull
:*:lien::line
:*:pienapple::pineapple
:*:enw::new
:*:ahck::hack
:*:hadn::hand
:*:thoguth::thought
:*:wiht::with
:*:decetn::decent
:*:mihgt::might
:*:seriosuly::seriously
:*:itner::inter
:*:fodler::folder
:*:teh::the
:*:ahnd::hand
:*:numebr::number
:*:;re::'re
:*:relaly::really
:*:caffiene::caffeine
:*:adn::and
:*:forogt::forgot
:*:things::things
:*:you;re::you're
:*:differnet::different
:*:alggy::laggy
:*:lsoe::lose
:*:alot::a lot
:*:aprt::part
:*:witht he::with the
:*:emial::email
:*:sahred::shared
:*:ebst::best
:*:whiel::while
:*:int he::in the
:*:alaways::always
:*:npa::nap
::eman::mean
:*:het::hey
:*:latered::altered
:*:gusy::guys
:*:slef::self
:*:ypu::yup
:*:amking::making
:*:ehavy::heavy
:*:publci::public
:*:samrt::smart
:*:wehn::when
:*:uplaod::upload
:*:iamge::image
:*:shirnk::shrink
:*:hoiw::how
:*:porcessed::processed
:*:pyhton::python
:*:thast::that's
:*:ona::on a
:*:likea::like a
:*:initail::initial
:*:relaod::reload
:*:thionk::think
:*:downlaod::download
:*:porbably::probably
:*:understadn::understand
::esp::especially
:*:recieve::receive
:*:comabt::combat
:*:popualr::popular
:*:yiou::you
:*:reciepe::recipe
:*:ofcourse::of course
:*:whihc::which
:*:hha::haha
:*:worng::wrong
:*:clikc::click
:*:neverous::nervous
:*:nayone::anyone
:*:shoudl::should
:*:auot::auto
:*:differetn::different
:*:amchine::machine
:*:[/c[::[/c]
:*:frogot::forgot
:*:fucntion::function
:*:repalce::replace
:*:alck::lack
:*:truning::turning
:*:ont he::no the
:*:redner::render
:*:stolskdorf::stolksdorf
:*:hadn::hand
:*:koisk::kiosk
:*:psot::post
:*:pwoer::power
:*:ahving::having
:*:machien::machine
:*:accoutn::account
:*:engien::engine
:*:plsu::plus
:*:logn::long
:*:elave::leave
:*:hwere::where
:*:awesoem::awesome
:*:itn::int
:*:daul::dual
::eff::efficiency
:*:pahse::phase
:*:psuh::push
:*:wokr::work
:*:remeber::remember
:*:muhc::much
:*:otehr::other
:*:assuem::assume
:*:googel::google
:*:canadain::canadian
:*:mkae::make
:*:Globla::Global
:*:fukc::fuck
:*:abby::baby
:*:bunhc::bunch
:*:satge::stage
:*:gettgin::getting
:*:roudn::round
:*:disbale::disable
:*:asnwer::answer
:*:radnom::random
:*:simpel::simple
::gte::get
:*:twon::town
:*:orgin::origin
:*:porper::proper
:*:becoem::become
:*:compelte::complete
:*:curretn::current
::obv::obviously
:*:welcoem::welcome
:*:exchnage::exchange
:*:assest::asset
:*:cahc::cach
:*:paycheque::paycheck
:*:realise::realize
:*:consloe::console
:*:cahnnel::channel
:*:oyu::you
:*:varibale::variable
:*:prok::pork
:*:amle::male
:*:proejcts::projects
:*:taek::take
:*:fiels::files
::fiel::file
:*:exampel::example
:*:acutally::actually
:*:tongiht::tonight
:*:inejct::inject
::bene::been
:*:workflowly::workflowy
:*:yuo::you
:*:stadn::stand
::falt::flat
:*:worht::worth
::fien::fine
:*:gaurd::guard
:*:defien::define
:*:knoiw::know
:*:notre::note
:*:+.::=>
:*:gti::git
:*:guage::gauge
:*:amn::man
::nad::and
::si::is
::abd::bad
:*:ehy::hey
:*:bakc::back
:*:paino::piano
:*:prefect::perfect
:*:nessicary::necessary
::otu::out
:*:luanch::launch
:*:saem::same
:*:pian::pain
:*:obejct::object
:*:4this::$this
:*:mostyl::mostly
:*:emthod::method
:*:constrcut::construct
:*:paln::plan
:*:<1--::<!--
:*:blod::bold
:*:lsuter::luster
:*:thuis::this
:*:amrk::mark
:*:swt::sweettooth
:*:arguement::argument
:*:paramter::parameter
:*:comapred::compared
:*:ahir::hair
:*:amtter::matter
:*:cliam::claim
:*:becasue::because
:*:cheif::chief
:*:conenction::connection
:*:rpove::prove
:*:throughrally::thoroughly
:*:tokne::token
:*:paltform::platform
:*:isntall::install
:*:wrost::worst
:*:tempplate::template
:*:tempalte::template
:*:seperate::separate
:*:teir::tier
:*:aht::hat
:*:vlaue::value
::alte::late
:*:amster::master
:*:toher::other
:*:campaing::campaign
:*:frameowrks::frameworks
:*:crtl::ctrl
:*:monday::Monday
:*:tuesday::Tuesday
:*:wednesday::Wednesday
:*:thursday::Thursday
:*:delious::delicious
:*:imporve::improve
:*:segement::segment
:*:sement::segment
:*:avergae::average
:*:tyepof::typeof
:*:frameowkr::framework
:*:gaem::game
:*:slwo::slow
:*:lolca::local
:*:cetner::center
:*:abolsute::absolute
:*:destory::destroy
:*:baldes::blades
:*:amek::make
:*:sloid::solid
::8?::*/
:*:samsh::smash
:*:nihgt::night
:*:whenveer::whenever
:*:eveyr::every
::dail::dial
:*:calcualtor::calculator
::nes::necessarily
:*:staph::stahp
:*:realitve::relative
:*:althoguh::although
:*:pseduo::pseudo
:*:alogirthm::algorithm
:*:alogithm::algorithm
:*:cathc::catch
:*:reuslt::result
::classNAme::className
:*:dinv::div
:*:onChnage::onChange
:*:conenct::connect
:*:_.amp::_.map
:*:shopfiy::shopify
:*:barkey::bakery
:*:pathc::patch
:*:proejct::project
:*:maek::make
:*:salck::slack
:*:tradiation::tradition
:*:Christina::Christian
:*:cosnt::const
:*:atuh::auth
:*:messanger::messenger
:*:+>::=>
:*:exmaple::example
:*:amgic::magic
:*:thrusday::Thursday
:*:sahll::shall
:*:inot::into
:*:foten::often
:*:ahngout::hangout
:*:nerveous::nervous
:*:hoyl::holy
:*:rpocess::process
:*:messgae::message
:*:leanred::learned
:*:samll::small
:*:tonihgt::tonight
:*:miuntes::minutes
:*:sjut::just
:*:pikc::pick
:*:tema::team
:*:mroe::more
:*:properities::properties
:*:colelction::collection
:*:amth::math
::ot::to
::hte::the
:*:cauhgt::caught
:*:componenet::component
:*:whiksy::whisky
::fro::for
:*:elarning::learning
:*:eyah::yeah
:*:cusotm::custom
:*:coudl::could
:*:swithc::switch
:*:wanrings::warnings
:*:actualyl::actually
:*:amin::main
:*:wanring::warning
:*:componenet::component
:*:ofr::for
:*:thikn::think
::dones;t::doesn't
::dosne;t::doesn't
:*:require9::require(
:*:lveo::love
:*:carasell::carousel
:*:scuh::such
:*:elarn::learn
:*:seperator::separator
:*:pcio::pico
:*:retunr::return
:*:wadswroth::wadsworth
:*:mathc::match
:*:agve::gave
:*:fihgt::fight
:*:everyhting::everything
:*:somehting::something
:*:borwser::browser
:*:fizle::fizzle
:*:simualte::simulate
:*:reutrn::return
:?:nee dto::need to
:*:hellosign::hellosign
:*:brokc::brock
:*:andriod::android
:*:elaving::leaving
:*:ahng::hang
:*:catalouge::catalogue
:*:sahre::share
:*:compoent::component
:*:compoennts::components
:*:gmae::game
:*:tbale::table
:*:modualr::modular
:*:caresoul::carousel
:*:appoitnment::appointment
:*:cabon::cabin
:*:doens;t::doesn't
:*:fantasty::fantasy
:*:calcualte::calculate
:*:comapny::company
:*:wathcing::watching
:*:bingalow::bungalow
:*:mian::main
::fo::of
:*:chekc::check
:*:colelcted::collected
:*:tot he::to the
:*:augur::auger
:*:collaspe::collapse
:*:Episilon::Epsilon
:*:calcualtion::calculation
:*:histroy::history
:*:locahost::localhost
:*:wrods::words
:*:researhc::research
:*:porblem::problem
:*:agianst::against
:*:teahc::teach
:*:netowrk::network
:*:colelcting::collecting
:*:debreif::debrief
:*:dialy::daily
:*:memebers::members
:*:Schrutika::Shrutika
:*:Shurtika::Shrutika
:*:probbaly::probably
:*:rpoduct::product
:*:verus::versus
:*:lattive::lattice
:*:chrips::chirps
:*:chrip::chirp
:*:axoim::axiom
:*:dashbaord::dashboard
:*:sqaud::squad
:*:csont::const
:*:captial::capital
:*:immedaite::immediate
:*:aorund::around
:*:dependacies::dependencies
:*:alternitive::alternative
:*:menaing::meaning
:*:nessecity::necessity
:*:alterntive::alternative
:*:maintence::maintaince
:*:nessicarily::necessarily
:*:paitent::patient
:*:prespective::perspective
:*:neruon::neuron
:*:OCean::Ocean
:*:comfortbale::comfortable
:*:differnt::different
:*:readbale::readable
:*:cuaght::caught
::doe snot::does not
::doens't::doesn't
::doesnt::doesn't
::dosen't::doesn't
::dosn't::doesn't
::doign::doing
:*:disbaling::disabling
:*:beofre::before
:*:snadbox::sandbox
:*:expoential::exponential
